//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineBusBookingSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookedList
    {
        public int BusId { get; set; }
        public int ReferenceNo { get; set; }
        public string Name { get; set; }
        public int Qty { get; set; }
        public int Amount { get; set; }
        public string Status { get; set; }
        public int ScheduleId { get; set; }
        public int UserId { get; set; }
        public bool IsCancelled { get; set; }
    
        public virtual BusList BusList { get; set; }
        public virtual Schedule Schedule { get; set; }
        public virtual User User { get; set; }
    }
}
